# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Ventana_Principal.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QSpacerItem, QSplitter, QStackedWidget, QStatusBar,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(766, 585)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.guardar = QAction(MainWindow)
        self.guardar.setObjectName(u"guardar")
        icon = QIcon(QIcon.fromTheme(u"document-save"))
        self.guardar.setIcon(icon)
        self.guardar_c = QAction(MainWindow)
        self.guardar_c.setObjectName(u"guardar_c")
        icon1 = QIcon(QIcon.fromTheme(u"document-save-as"))
        self.guardar_c.setIcon(icon1)
        self.cerrar = QAction(MainWindow)
        self.cerrar.setObjectName(u"cerrar")
        icon2 = QIcon(QIcon.fromTheme(u"edit-clear"))
        self.cerrar.setIcon(icon2)
        self.copiar = QAction(MainWindow)
        self.copiar.setObjectName(u"copiar")
        icon3 = QIcon(QIcon.fromTheme(u"edit-copy"))
        self.copiar.setIcon(icon3)
        self.cortar = QAction(MainWindow)
        self.cortar.setObjectName(u"cortar")
        icon4 = QIcon(QIcon.fromTheme(u"edit-cut"))
        self.cortar.setIcon(icon4)
        self.pegar = QAction(MainWindow)
        self.pegar.setObjectName(u"pegar")
        icon5 = QIcon(QIcon.fromTheme(u"edit-paste"))
        self.pegar.setIcon(icon5)
        self.selec_todo = QAction(MainWindow)
        self.selec_todo.setObjectName(u"selec_todo")
        icon6 = QIcon(QIcon.fromTheme(u"edit-select-all"))
        self.selec_todo.setIcon(icon6)
        self.rehacer = QAction(MainWindow)
        self.rehacer.setObjectName(u"rehacer")
        icon7 = QIcon(QIcon.fromTheme(u"edit-redo"))
        self.rehacer.setIcon(icon7)
        self.deshacer = QAction(MainWindow)
        self.deshacer.setObjectName(u"deshacer")
        icon8 = QIcon(QIcon.fromTheme(u"document-revert"))
        self.deshacer.setIcon(icon8)
        self.a_lexico = QAction(MainWindow)
        self.a_lexico.setObjectName(u"a_lexico")
        self.a_sintactico = QAction(MainWindow)
        self.a_sintactico.setObjectName(u"a_sintactico")
        self.AbrirArchivo = QAction(MainWindow)
        self.AbrirArchivo.setObjectName(u"AbrirArchivo")
        icon9 = QIcon(QIcon.fromTheme(u"document-open"))
        self.AbrirArchivo.setIcon(icon9)
        self.AbrirCarpeta = QAction(MainWindow)
        self.AbrirCarpeta.setObjectName(u"AbrirCarpeta")
        icon10 = QIcon(QIcon.fromTheme(u"folder-open"))
        self.AbrirCarpeta.setIcon(icon10)
        self.NuevoArchivo = QAction(MainWindow)
        self.NuevoArchivo.setObjectName(u"NuevoArchivo")
        icon11 = QIcon(QIcon.fromTheme(u"document-new"))
        self.NuevoArchivo.setIcon(icon11)
        self.NuevaCarpeta = QAction(MainWindow)
        self.NuevaCarpeta.setObjectName(u"NuevaCarpeta")
        icon12 = QIcon(QIcon.fromTheme(u"folder-new"))
        self.NuevaCarpeta.setIcon(icon12)
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.Acerca_de = QAction(MainWindow)
        self.Acerca_de.setObjectName(u"Acerca_de")
        self.actionOscuro = QAction(MainWindow)
        self.actionOscuro.setObjectName(u"actionOscuro")
        self.actionClaro = QAction(MainWindow)
        self.actionClaro.setObjectName(u"actionClaro")
        self.ventana = QWidget(MainWindow)
        self.ventana.setObjectName(u"ventana")
        self.gridLayout = QGridLayout(self.ventana)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.widget_2 = QWidget(self.ventana)
        self.widget_2.setObjectName(u"widget_2")
        self.horizontalLayout_6 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.BtnNvo = QPushButton(self.widget_2)
        self.BtnNvo.setObjectName(u"BtnNvo")
        self.BtnNvo.setMinimumSize(QSize(0, 0))
        self.BtnNvo.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.BtnNvo.setIconSize(QSize(25, 25))

        self.horizontalLayout_6.addWidget(self.BtnNvo)

        self.BtnGuardar = QPushButton(self.widget_2)
        self.BtnGuardar.setObjectName(u"BtnGuardar")
        self.BtnGuardar.setMinimumSize(QSize(0, 0))
        self.BtnGuardar.setIconSize(QSize(25, 25))

        self.horizontalLayout_6.addWidget(self.BtnGuardar)

        self.BtnEjecutar = QPushButton(self.widget_2)
        self.BtnEjecutar.setObjectName(u"BtnEjecutar")
        self.BtnEjecutar.setIconSize(QSize(25, 25))

        self.horizontalLayout_6.addWidget(self.BtnEjecutar)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer)


        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)

        self.stackedWidget = QStackedWidget(self.ventana)
        self.stackedWidget.setObjectName(u"stackedWidget")
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.horizontalLayout = QHBoxLayout(self.page)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.splitter = QSplitter(self.page)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.verticalLayoutWidget = QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.treeview = QVBoxLayout(self.verticalLayoutWidget)
        self.treeview.setObjectName(u"treeview")
        self.treeview.setContentsMargins(0, 0, 0, 0)
        self.splitter.addWidget(self.verticalLayoutWidget)
        self.codigo = QTabWidget(self.splitter)
        self.codigo.setObjectName(u"codigo")
        sizePolicy.setHeightForWidth(self.codigo.sizePolicy().hasHeightForWidth())
        self.codigo.setSizePolicy(sizePolicy)
        self.codigo.setMinimumSize(QSize(300, 10))
        self.codigo.setMaximumSize(QSize(16777215, 16777215))
        self.codigo.setStyleSheet(u"")
        self.codigo.setTabsClosable(True)
        self.codigo.setMovable(True)
        self.splitter.addWidget(self.codigo)
        self.widget = QWidget(self.splitter)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(200, 0))
        self.widget.setMaximumSize(QSize(600, 16777215))
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.analisis = QTabWidget(self.widget)
        self.analisis.setObjectName(u"analisis")
        self.analisis.setMaximumSize(QSize(16777215, 16777215))
        self.analisis.setTabsClosable(True)
        self.analisis.setMovable(True)
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.verticalLayout_3 = QVBoxLayout(self.tab_5)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.analisis.addTab(self.tab_5, "")

        self.verticalLayout.addWidget(self.analisis)

        self.splitter.addWidget(self.widget)

        self.horizontalLayout.addWidget(self.splitter)

        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.stackedWidget.addWidget(self.page_2)

        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.ventana)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 766, 33))
        self.archivo = QMenu(self.menubar)
        self.archivo.setObjectName(u"archivo")
        self.menuAbrir = QMenu(self.archivo)
        self.menuAbrir.setObjectName(u"menuAbrir")
        self.menuNuevo = QMenu(self.archivo)
        self.menuNuevo.setObjectName(u"menuNuevo")
        self.edicion = QMenu(self.menubar)
        self.edicion.setObjectName(u"edicion")
        self.analizar = QMenu(self.menubar)
        self.analizar.setObjectName(u"analizar")
        self.menuAyuda = QMenu(self.menubar)
        self.menuAyuda.setObjectName(u"menuAyuda")
        self.menuVentana = QMenu(self.menubar)
        self.menuVentana.setObjectName(u"menuVentana")
        self.menuCambiar_Tema = QMenu(self.menuVentana)
        self.menuCambiar_Tema.setObjectName(u"menuCambiar_Tema")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.archivo.menuAction())
        self.menubar.addAction(self.edicion.menuAction())
        self.menubar.addAction(self.analizar.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.menubar.addAction(self.menuVentana.menuAction())
        self.archivo.addAction(self.menuAbrir.menuAction())
        self.archivo.addAction(self.menuNuevo.menuAction())
        self.archivo.addAction(self.guardar)
        self.archivo.addAction(self.guardar_c)
        self.archivo.addAction(self.cerrar)
        self.archivo.addSeparator()
        self.menuAbrir.addAction(self.AbrirArchivo)
        self.menuAbrir.addAction(self.AbrirCarpeta)
        self.menuNuevo.addAction(self.NuevoArchivo)
        self.menuNuevo.addAction(self.NuevaCarpeta)
        self.edicion.addAction(self.copiar)
        self.edicion.addAction(self.cortar)
        self.edicion.addAction(self.pegar)
        self.edicion.addAction(self.selec_todo)
        self.edicion.addAction(self.rehacer)
        self.edicion.addAction(self.deshacer)
        self.edicion.addSeparator()
        self.analizar.addAction(self.a_lexico)
        self.analizar.addAction(self.a_sintactico)
        self.analizar.addSeparator()
        self.menuAyuda.addAction(self.Acerca_de)
        self.menuVentana.addAction(self.menuCambiar_Tema.menuAction())
        self.menuCambiar_Tema.addAction(self.actionOscuro)
        self.menuCambiar_Tema.addAction(self.actionClaro)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.codigo.setCurrentIndex(-1)
        self.analisis.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.guardar.setText(QCoreApplication.translate("MainWindow", u"Guardar ", None))
#if QT_CONFIG(shortcut)
        self.guardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.guardar_c.setText(QCoreApplication.translate("MainWindow", u"Guadar como", None))
#if QT_CONFIG(shortcut)
        self.guardar_c.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.cerrar.setText(QCoreApplication.translate("MainWindow", u"Cerrar", None))
#if QT_CONFIG(shortcut)
        self.cerrar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.copiar.setText(QCoreApplication.translate("MainWindow", u"Copiar", None))
#if QT_CONFIG(shortcut)
        self.copiar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.cortar.setText(QCoreApplication.translate("MainWindow", u"Cortar", None))
#if QT_CONFIG(shortcut)
        self.cortar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.pegar.setText(QCoreApplication.translate("MainWindow", u"Pegar", None))
#if QT_CONFIG(shortcut)
        self.pegar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.selec_todo.setText(QCoreApplication.translate("MainWindow", u"Seleccionar todo", None))
#if QT_CONFIG(shortcut)
        self.selec_todo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.rehacer.setText(QCoreApplication.translate("MainWindow", u"Rehacer", None))
#if QT_CONFIG(shortcut)
        self.rehacer.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.deshacer.setText(QCoreApplication.translate("MainWindow", u"Deshacer", None))
#if QT_CONFIG(shortcut)
        self.deshacer.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.a_lexico.setText(QCoreApplication.translate("MainWindow", u"Analizador L\u00e9xico", None))
        self.a_sintactico.setText(QCoreApplication.translate("MainWindow", u"Analizador Sint\u00e1ctico", None))
        self.AbrirArchivo.setText(QCoreApplication.translate("MainWindow", u"Archivo", None))
#if QT_CONFIG(shortcut)
        self.AbrirArchivo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O, Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.AbrirCarpeta.setText(QCoreApplication.translate("MainWindow", u"Carpeta", None))
#if QT_CONFIG(shortcut)
        self.AbrirCarpeta.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O, Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.NuevoArchivo.setText(QCoreApplication.translate("MainWindow", u"Archivo", None))
#if QT_CONFIG(shortcut)
        self.NuevoArchivo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N, Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.NuevaCarpeta.setText(QCoreApplication.translate("MainWindow", u"Carpeta", None))
#if QT_CONFIG(shortcut)
        self.NuevaCarpeta.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N, Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.action.setText(QCoreApplication.translate("MainWindow", u"Desarrolladores:", None))
        self.Acerca_de.setText(QCoreApplication.translate("MainWindow", u"Acerca de Py\u00f1a Code", None))
        self.actionOscuro.setText(QCoreApplication.translate("MainWindow", u"Oscuro", None))
        self.actionClaro.setText(QCoreApplication.translate("MainWindow", u"Claro", None))
#if QT_CONFIG(tooltip)
        self.BtnNvo.setToolTip(QCoreApplication.translate("MainWindow", u"Nuevo  Archivo", None))
#endif // QT_CONFIG(tooltip)
        self.BtnNvo.setText("")
#if QT_CONFIG(tooltip)
        self.BtnGuardar.setToolTip(QCoreApplication.translate("MainWindow", u"Guardar", None))
#endif // QT_CONFIG(tooltip)
        self.BtnGuardar.setText("")
#if QT_CONFIG(tooltip)
        self.BtnEjecutar.setToolTip(QCoreApplication.translate("MainWindow", u"Ejecutar", None))
#endif // QT_CONFIG(tooltip)
        self.BtnEjecutar.setText("")
        self.analisis.setTabText(self.analisis.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.archivo.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
        self.menuAbrir.setTitle(QCoreApplication.translate("MainWindow", u"Abrir", None))
        self.menuNuevo.setTitle(QCoreApplication.translate("MainWindow", u"Nuevo", None))
        self.edicion.setTitle(QCoreApplication.translate("MainWindow", u"Edicion", None))
        self.analizar.setTitle(QCoreApplication.translate("MainWindow", u"Analizar", None))
        self.menuAyuda.setTitle(QCoreApplication.translate("MainWindow", u"Ayuda", None))
        self.menuVentana.setTitle(QCoreApplication.translate("MainWindow", u"Ventana", None))
        self.menuCambiar_Tema.setTitle(QCoreApplication.translate("MainWindow", u"Cambiar Tema", None))
    # retranslateUi

